### ISSUE TITLE
登录后的bug

### ISSUE THREAD

**Issue by Yakumo-Yukari** [chalvern/apollo#2]
![112](https://user-images.githubusercontent.com/12076232/74296467-e3b92080-4d7e-11ea-9ccd-7ea9a9470096.PNG)

![123](https://user-images.githubusercontent.com/12076232/74296460-def46c80-4d7e-11ea-8032-d36affa4360c.PNG)

在用户登录后 没有发帖按钮（发帖权限？），登录后帖内依然无法回复 提示登录后评论

**Comment by chalvern** [comment]
应该是因为没有权限，这里打算后面加邮箱验证后赋予最基础的权限。目前后台手动增加了基础的权限，可以试试看。

**Comment by Yakumo-Yukari** [comment]
> 应该是因为没有权限，这里打算后面加邮箱验证后赋予最基础的权限。目前后台手动增加了基础的权限，可以试试看。

当前使用的发帖形式 是 文章分享吧 没有常见的社区 帖子类型吗
