### ISSUE TITLE
建议把那个交互的通知信息中心加上去

### ISSUE THREAD

**Issue by ff678liu** [chalvern/apollo#5]
建议把那个交互的通知信息中心加上去
我做了一个简单版 

![image](https://user-images.githubusercontent.com/29591794/77772256-ccaa6580-7082-11ea-8a1e-c59baaa577e8.png)

感觉设计的有有问题 如果基于这个表来查的话 可能每个字段都要加索引了
![image](https://user-images.githubusercontent.com/29591794/77772524-3c205500-7083-11ea-9ba3-3bcaf51900f2.png)

**Comment by chalvern** [comment]
通知中心后面考虑一下。不过不太懂你的设计思路，也没有找到你相关的代码库呀。

我的思路，通知这里可以模仿一些现成的论坛，比如我比较喜欢的 rails 生态里的 [ruby-china](https://github.com/ruby-china/homeland) 这个项目
