### ISSUE TITLE
jwt中间件请求时的查询用户sql语句，如何缓存？

### ISSUE THREAD

**Issue by Insua** [chalvern/apollo#6]
中间件已经请求过异常sql查询了，如果在控制器里再次需要根据jwt token获取用户，那需要再查询一次sql，这就造成冗余了，如何缓存住这次查询，在控制器里获取用户时 不需要查询sql 就可以获取用户？

**Comment by chalvern** [comment]
如果你的用户量不大，这一次冗余其实也还好。有几个理由：
1. 数据库那里自动就会有缓存，第一次 select 的时候可能会比较耗时，但是后面的请求数据库大概率会命中sql直接返回；
1. 一般情况下一个请求过来可能会去包含很多个sql，降低这一个对整个系统的优化作用可能不会太大。
1. 如果非要缓存，那么可以考虑把检索出来的用户信息存到内存型数据库redis里去，这样每次不用从 mysql 拿，直接去 redis 拿。但是这种设计会增加系统复杂度，比如你至少要搞一套机制同步 mysql 与 redis 二者的数据一致性。
1. 最后一种安全上需要评估的用法是，把用户数据存到 jwt 里去，每个请求过来的时候直接从 jwt 解出来；不过因为 jwt 几乎是明文存储（body部分是简单的base64编码），这种方案需要很小心。

**Comment by Insua** [comment]
我这几年都是用php laravel 开发的 laravel 使用 Auth::user() 获取授权用户后，在这次请求后无论怎么访问 都不会再去查询sql了，翻了源码 没看懂 laravel 怎么实现的 😳

**Comment by chalvern** [comment]
@Insua 如果没有配置 redis 这类内存型数据库，我估摸着是这么个原理：单实例里检出用户数据后保存到一个临时内存里，只要后面有相同用户的请求过来，直接就从这块内存里拿出来。

其实相当于 php 设计了一个简单的内存数据库。本质上和配置 redis 是一样的，你可以部署两个实例试试，两个实例上第一个请求应该都会有 sql 查询，然后每个实例都缓存一份用户信息到本地。

**Comment by Insua** [comment]
@chalvern 用go的单例模式能否实现？会不会造成多个请求都去得到了同一个用户的数据信息？

**Comment by chalvern** [comment]
这个不是单例的问题，而是怎么存储的问题。

比如你实现这么一种单例的设计：你创建一个类型为 [sync.Map](https://golang.google.cn/pkg/sync/#Map)(需要并发安全，所以不能用原声的 map）的单例，每次请求来了你到 syncmap 中查，如果没有对应的用户信息就去数据库拿。

不过为了能用在生产环境，你自己得考虑怎么让用户数据过期，不然会内存越来越大最后撑爆机器。
