### ISSUE TITLE
请问这个项目有没有api接口

### ISSUE THREAD

**Issue by dengbin9009** [chalvern/apollo#7]
比如直接通过一个接口获取json格式的share列表

**Comment by chalvern** [comment]
> 比如直接通过一个接口获取json格式的share列表

没有的。当年想着加来着，但是苦于精力有限就没加上去。。

**Comment by dengbin9009** [comment]
好吧 可惜了，要是前后端分离，就更好的
但是这也是一个很好的项目，非常适合我这种新手食用
